//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef _TtC5FSKit38_FSKitFileSystemExtensionConfiguration_h
#define _TtC5FSKit38_FSKitFileSystemExtensionConfiguration_h
@import Foundation;

@class _$sSo17FSModuleExtensionC;

@interface _TtC5FSKit38_FSKitFileSystemExtensionConfiguration : NSObject { // (Swift)
    /* instance variables */
    _$sSo17FSModuleExtensionC ourExtension;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC5FSKit38_FSKitFileSystemExtensionConfiguration_h */
