//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSActivationOptionSyntax_h
#define FSActivationOptionSyntax_h
@import Foundation;

@interface FSActivationOptionSyntax : NSObject

@property (retain) NSArray *options;

/* class methods */
+ (id)allOptionNames:(id)names;
+ (id)argTypeFromDictionary:(id)dictionary;
+ (id)parseOptionFromData:(id)data;
+ (id)stringForOption:(id)option inOptions:(id)options;
+ (id)stringFromDictionary:(id)dictionary key:(id)key;
+ (id)systemMountOptions;

/* instance methods */
- (id)initWithOptions:(id)options;
- (id)optionWithName:(id)name;
- (id)initWithAttributeData:(id)data;
- (id)validateOptions:(id)options;

@end

#endif /* FSActivationOptionSyntax_h */
