//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSActivationOption_h
#define FSActivationOption_h
@import Foundation;

@interface FSActivationOption : NSObject

@property (retain) NSString *name;
@property long long argumentType;
@property (retain) NSString *defaultValue;

/* class methods */
+ (id)optionWithName:(id)name argumentType:(long long)type defaultValue:(id)value;

/* instance methods */

@end

#endif /* FSActivationOption_h */
