//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSAgentXPC_Protocol_h
#define FSAgentXPC_Protocol_h
@import Foundation;

@protocol FSAgentXPC <NSObject>

@required

/* required instance methods */
- (void)getNSXPCListenerEndpoint:(id)endpoint instanceID:(id)id replyHandler:(id /* block */)handler;
- (void)installedExtensions:(id /* block */)extensions;
- (void)setEnabledState:(id)state newState:(_Bool)state replyHandler:(id /* block */)handler;
- (void)startExtension:(id)extension instanceID:(id)id replyHandler:(id /* block */)handler;
- (void)stopExtension:(id)extension instanceID:(id)id replyHandler:(id /* block */)handler;

@optional

@end

#endif /* FSAgentXPC_Protocol_h */
