//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSAgentClientDelegate_h
#define FSAgentClientDelegate_h
@import Foundation;

#include "FSAgentHostXPC-Protocol.h"

@interface FSAgentClientDelegate : NSObject <FSAgentHostXPC>

@property (copy) id /* block */ instanceDeathHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)instanceExited:(id)exited instanceUUID:(id)uuid;

@end

#endif /* FSAgentClientDelegate_h */
