//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSBlockDeviceResource_h
#define FSBlockDeviceResource_h
@import Foundation;

#include "FSResource.h"
#include "FSWorkQueue.h"

@protocol OS_dispatch_queue;

@interface FSBlockDeviceResource : FSResource {
    /* instance variables */
    _Bool _supportsBarrier;
    _Bool _supportsPriority;
    _Bool _supportsUnmap;
    unsigned long long _queueDepth;
}

@property (readonly) NSString *devicePath;
@property (readonly) unsigned long long partitionBase;
@property (readonly) _Bool isSSD;
@property (readonly) int fileDescriptor;
@property (readonly, nonatomic) NSString *bsdName;
@property (readonly, nonatomic) _Bool terminated;
@property _Bool limited;
@property (retain) FSWorkQueue *fsExecQueue;
@property (readonly) NSString *devicePath;
@property (readonly) int fileDescriptor;
@property (readonly) unsigned long long partitionBase;
@property (readonly) _Bool isSSD;
@property unsigned int notification;
@property struct IONotificationPort * notifyPort;
@property (retain) NSObject<OS_dispatch_queue> *ioKitQueue;
@property (retain) NSString *usingResourcePurpose;
@property _Bool limited;
@property (readonly, copy) NSString *BSDName;
@property (readonly) _Bool writable;
@property (readonly) unsigned long long blockSize;
@property (readonly) unsigned long long blockCount;
@property (readonly) unsigned long long physicalBlockSize;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)getDeviceName:(id)name;
+ (id)newProxyForBSDName:(id)bsdname isWritable:(_Bool)writable;
+ (void)openWithBSDName:(id)bsdname writable:(_Bool)writable auditToken:(id)token replyHandler:(id /* block */)handler;
+ (id)proxyResourceForBSDName:(id)bsdname;
+ (id)proxyResourceForBSDName:(id)bsdname isWritable:(_Bool)writable;
+ (id)resourceWithBSDName:(id)bsdname devicePath:(id)path fileDescriptor:(int)descriptor writable:(_Bool)writable;

/* instance methods */
- (void)terminate;
- (long long)kind;
- (_Bool)isWritable;
- (id)initWithResource:(id)resource;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (id)makeProxy;
- (void)revoke;
- (id)initProxyForBSDName:(id)bsdname isWritable:(_Bool)writable;
- (void)terminateLocked;
- (_Bool)asynchronousMetadataFlushWithError:(id *)error;
- (_Bool)delayedMetadataWriteFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (id)getProgressURLKey;
- (id)getResourceID;
- (id)initProxyForBSDName:(id)bsdname;
- (id)initWithBSDName:(id)bsdname devicePath:(id)path fileDescriptor:(int)descriptor writable:(_Bool)writable;
- (_Bool)metadataClear:(id)clear withDelayedWrites:(_Bool)writes error:(id *)error;
- (_Bool)metadataFlushWithError:(id *)error;
- (_Bool)metadataPurge:(id)purge error:(id *)error;
- (_Bool)metadataReadInto:(void *)into startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (_Bool)metadataReadInto:(void *)into startingAt:(long long)at length:(unsigned long long)length readAheadExtents:(const struct { long long x0; unsigned long long x1; } *)extents readAheadCount:(long long)count error:(id *)error;
- (_Bool)metadataWriteFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (void)readFirstSectorAndLog;
- (void)readInto:(void *)into startingAt:(long long)at length:(unsigned long long)length completionHandler:(id /* block */)handler;
- (unsigned long long)readInto:(void *)into startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (void)releaseNotification;
- (id)startUsingResource:(id)resource;
- (id)stopUsingResource:(id)resource;
- (void)writeFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length completionHandler:(id /* block */)handler;
- (unsigned long long)writeFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length error:(id *)error;

@end

#endif /* FSBlockDeviceResource_h */
