//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSBlockDeviceBufferResource_h
#define FSBlockDeviceBufferResource_h
@import Foundation;

#include "FSBlockDeviceResource.h"

@interface FSBlockDeviceBufferResource : FSBlockDeviceResource

@property (readonly) NSMutableData *buffer;
@property (readonly) long long headerLength;
@property (readonly) long long footerLength;
@property (readonly) long long size;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)bufferFromResource:(id)resource;
+ (id)dynamicCast:(id)cast;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (_Bool)asynchronousMetadataFlushWithError:(id *)error;
- (_Bool)delayedMetadataWriteFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (id)initBufferFromResource:(id)resource;
- (_Bool)metadataClear:(id)clear withDelayedWrites:(_Bool)writes error:(id *)error;
- (_Bool)metadataFlushWithError:(id *)error;
- (_Bool)metadataPurge:(id)purge error:(id *)error;
- (_Bool)metadataReadInto:(void *)into startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (_Bool)metadataReadInto:(void *)into startingAt:(long long)at length:(unsigned long long)length readAheadExtents:(const struct { long long x0; unsigned long long x1; } *)extents readAheadCount:(long long)count error:(id *)error;
- (_Bool)metadataWriteFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (void)readInto:(void *)into startingAt:(long long)at length:(unsigned long long)length completionHandler:(id /* block */)handler;
- (unsigned long long)readInto:(void *)into startingAt:(long long)at length:(unsigned long long)length error:(id *)error;
- (void)writeFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length completionHandler:(id /* block */)handler;
- (unsigned long long)writeFrom:(void *)from startingAt:(long long)at length:(unsigned long long)length error:(id *)error;

@end

#endif /* FSBlockDeviceBufferResource_h */
