//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSClientTaskUpdateHandler_h
#define FSClientTaskUpdateHandler_h
@import Foundation;

#include "FSClientHostXPC-Protocol.h"

@interface FSClientTaskUpdateHandler : NSObject <FSClientHostXPC>

@property (copy) id /* block */ taskHandler;

/* instance methods */
- (void)taskStatusUpdate:(id)update;

@end

#endif /* FSClientTaskUpdateHandler_h */
