//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSClientHostXPC_Protocol_h
#define FSClientHostXPC_Protocol_h
@import Foundation;

@protocol FSClientHostXPC

@required

/* required instance methods */
- (void)taskStatusUpdate:(id)update;

@optional

@end

#endif /* FSClientHostXPC_Protocol_h */
