//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSContainerStatus_h
#define FSContainerStatus_h
@import Foundation;

@interface FSContainerStatus : NSObject <NSCopying>

@property (readonly) long long state;
@property (readonly, copy) NSError *status;

/* class methods */
+ (id)ready;
+ (id)active;
+ (id)activeWithStatus:(id)status;
+ (id)blockedWithStatus:(id)status;
+ (id)notReadyWithStatus:(id)status;
+ (id)readyWithStatus:(id)status;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithState:(long long)state status:(id)status;

@end

#endif /* FSContainerStatus_h */
