//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSContainerIdentifier_h
#define FSContainerIdentifier_h
@import Foundation;

#include "FSEntityIdentifier.h"
#include "FSVolumeIdentifier.h"

@interface FSContainerIdentifier : FSEntityIdentifier

@property (readonly, copy) FSVolumeIdentifier *volumeIdentifier;

@end

#endif /* FSContainerIdentifier_h */
