//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSConnectorMaker_Protocol_h
#define FSConnectorMaker_Protocol_h
@import Foundation;

@protocol FSConnectorMaker

@required

/* class methods */
+ (id)newExportObjectForObject:(id)object connection:(id)connection error:(id *)error;

/* required instance methods */
- (void)connectionWasInterrupted;
- (void)connectionWasInvalidated;

@optional

@end

#endif /* FSConnectorMaker_Protocol_h */
