//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSConnectShareTask_h
#define FSConnectShareTask_h
@import Foundation;

#include "FSTask.h"
#include "FSVolume.h"

@interface FSConnectShareTask : FSTask

@property (retain) FSVolume *result;

/* instance methods */
- (void)didCompleteWithVolume:(id)volume;

@end

#endif /* FSConnectShareTask_h */
