//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSDirectoryEntryPacker_h
#define FSDirectoryEntryPacker_h
@import Foundation;

#include "FSMutableFileDataBuffer.h"

@interface FSDirectoryEntryPacker : NSObject {
    /* instance variables */
    void * _lastEntry;
}

@property (readonly) long long bytesPacked;
@property (readonly) _Bool withAttributes;
@property (readonly) _Bool outOfSpace;
@property long long bytesPacked;
@property (retain) FSMutableFileDataBuffer *buffer;
@property _Bool outOfSpace;
@property _Bool withAttributes;

/* instance methods */
- (id)initWithBuffer:(id)buffer withAttributes:(_Bool)attributes;
- (_Bool)packEntryWithName:(id)name itemType:(long long)type itemID:(unsigned long long)id nextCookie:(unsigned long long)cookie attributes:(id)attributes;
- (void)setLastEntryAsEOF;

@end

#endif /* FSDirectoryEntryPacker_h */
