//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSEntityIdentifier_h
#define FSEntityIdentifier_h
@import Foundation;

@interface FSEntityIdentifier : NSObject <NSCopying, NSSecureCoding>

@property (readonly, nonatomic) NSData *uuidData;
@property (copy) NSUUID *uuid;
@property (copy) NSData *qualifier;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)defaultInstanceUUID;

/* instance methods */
- (id)initWithUUID:(id)uuid;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)init;
- (Class)classForCoder;
- (id)description;
- (id)initWithCoder:(id)coder;
- (id)initWithUUID:(id)uuid data:(id)data;
- (id)initWithCopiedUUID:(id)uuid data:(id)data;
- (id)initWithUUID:(id)uuid qualifier:(unsigned long long)qualifier;

@end

#endif /* FSEntityIdentifier_h */
