//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSEnumeratedSharePacker_h
#define FSEnumeratedSharePacker_h
@import Foundation;

@interface FSEnumeratedSharePacker : NSObject

/* instance methods */
- (_Bool)packShareWithName:(id)name info:(id)info;

@end

#endif /* FSEnumeratedSharePacker_h */
