//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSExtentPacker_h
#define FSExtentPacker_h
@import Foundation;

@interface FSExtentPacker : NSObject

@property unsigned int bytesPacked;
@property (retain) NSMutableData *buffer;
@property long long extentsPacked;
@property _Bool outOfSpace;

/* instance methods */
- (id)initWithLength:(unsigned long long)length;
- (id)extentData;
- (id)extentDataByExtentsPacked;
- (id)initWithBlockmapFlags:(unsigned long long)flags;
- (id)initWithExtentCount:(unsigned long long)count;
- (_Bool)packExtentWithResource:(id)resource type:(long long)type logicalOffset:(long long)offset physicalOffset:(long long)offset length:(unsigned long long)length;

@end

#endif /* FSExtentPacker_h */
