//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSFileSystem_h
#define FSFileSystem_h
@import Foundation;

#include "FSContainerStatus.h"
#include "FSFileSystemBase-Protocol.h"
#include "FSModuleExtension.h"

@interface FSFileSystem : NSObject <FSFileSystemBase>

@property (retain) FSModuleExtension *extension;
@property (copy) FSContainerStatus *containerStatus;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)wipeResource:(id)resource completionHandler:(id /* block */)handler;

@end

#endif /* FSFileSystem_h */
