//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSFileSystemBasis_h
#define FSFileSystemBasis_h
@import Foundation;

#include "FSModuleExtension.h"

@interface FSFileSystemBasis : NSObject

@property (retain) FSModuleExtension *extension;

/* class methods */
+ (void)wipeResource:(id)resource extension:(id)extension completionHandler:(id /* block */)handler;

/* instance methods */

@end

#endif /* FSFileSystemBasis_h */
