//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSFileName_h
#define FSFileName_h
@import Foundation;

@interface FSFileName : NSObject <NSSecureCoding, NSCopying>

@property (retain, nonatomic) NSData *data;
@property (readonly) NSString *string;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)nameWithString:(id)string;
+ (id)nameWithBytes:(const char *)bytes length:(unsigned long long)length;
+ (id)nameWithCString:(const char *)cstring;
+ (id)nameWithData:(id)data;

/* instance methods */
- (id)initWithBytes:(const char *)bytes length:(unsigned long long)length;
- (id)initWithString:(id)string;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithData:(id)data;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCString:(const char *)cstring;
- (unsigned long long)hash;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;

@end

#endif /* FSFileName_h */
