//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSFileHandle_h
#define FSFileHandle_h
@import Foundation;

@interface FSFileHandle : NSObject <NSSecureCoding, NSCopying>

@property (nonatomic) unsigned long long value;
@property (readonly, copy, nonatomic) NSString *base64String;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithValue:(unsigned long long)value;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;

@end

#endif /* FSFileHandle_h */
