//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSItemSetAttributesRequest_h
#define FSItemSetAttributesRequest_h
@import Foundation;

#include "FSItemAttributes.h"

@interface FSItemSetAttributesRequest : FSItemAttributes

@property (nonatomic) long long consumedAttributes;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)init;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (_Bool)wasAttributeConsumed:(long long)consumed;

@end

#endif /* FSItemSetAttributesRequest_h */
