//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSItem_h
#define FSItem_h
@import Foundation;

#include "FSFileHandle.h"

@interface FSItem : NSObject

@property (retain) FSFileHandle *fileHandle;
@property (nonatomic) long long type;

/* instance methods */
- (id)init;

@end

#endif /* FSItem_h */
