//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSItemTriple_h
#define FSItemTriple_h
@import Foundation;

@interface FSItemTriple : NSObject <NSCopying>

@property (readonly, retain) NSObject *first;
@property (readonly, retain) NSObject *second;
@property (readonly, retain) NSObject *third;

/* class methods */
+ (id)tripleWith:(id)with second:(id)second third:(id)third;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWith:(id)with second:(id)second third:(id)third;

@end

#endif /* FSItemTriple_h */
