//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSItemGetAttributesRequest_h
#define FSItemGetAttributesRequest_h
@import Foundation;

@interface FSItemGetAttributesRequest : NSObject <NSSecureCoding>

@property (nonatomic) long long wantedAttributes;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)init;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (id)initWithWantedFSAttributes:(unsigned long long)fsattributes;
- (_Bool)isAttributeWanted:(long long)wanted;

@end

#endif /* FSItemGetAttributesRequest_h */
