//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSItemAttributes_h
#define FSItemAttributes_h
@import Foundation;

@interface FSItemAttributes : NSObject <NSSecureCoding> {
    /* instance variables */
    struct _FSFileAttributes { unsigned long long __fa_rsvd0; unsigned long long fa_validmask; unsigned long long fa_seqno; unsigned int fa_type; unsigned int fa_mode; unsigned int fa_nlink; unsigned int fa_uid; unsigned int fa_gid; unsigned int fa_bsd_flags; unsigned long long fa_size; unsigned long long fa_allocsize; unsigned long long fa_fileid; unsigned long long fa_parentid; struct timespec { long long tv_sec; long long tv_nsec; } fa_atime; struct timespec { long long tv_sec; long long tv_nsec; } fa_mtime; struct timespec { long long tv_sec; long long tv_nsec; } fa_ctime; struct timespec { long long tv_sec; long long tv_nsec; } fa_birthtime; struct timespec { long long tv_sec; long long tv_nsec; } fa_backuptime; struct timespec { long long tv_sec; long long tv_nsec; } fa_addedtime; unsigned int fa_int_flags; unsigned int _pad0; } attrs;
}

@property (nonatomic) unsigned int uid;
@property (nonatomic) unsigned int gid;
@property (nonatomic) unsigned int mode;
@property (nonatomic) long long type;
@property (nonatomic) unsigned int linkCount;
@property (nonatomic) unsigned int flags;
@property (nonatomic) unsigned long long size;
@property (nonatomic) unsigned long long allocSize;
@property (nonatomic) unsigned long long fileID;
@property (nonatomic) unsigned long long parentID;
@property (nonatomic) _Bool supportsLimitedXAttrs;
@property (nonatomic) _Bool inhibitKernelOffloadedIO;
@property (nonatomic) struct timespec { long long x0; long long x1; } modifyTime;
@property (nonatomic) struct timespec { long long x0; long long x1; } addedTime;
@property (nonatomic) struct timespec { long long x0; long long x1; } changeTime;
@property (nonatomic) struct timespec { long long x0; long long x1; } accessTime;
@property (nonatomic) struct timespec { long long x0; long long x1; } birthTime;
@property (nonatomic) struct timespec { long long x0; long long x1; } backupTime;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)requestWithData:(id)data;
+ (id)requestWithFSAttributes:(const struct _FSFileAttributes { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; unsigned long long x9; unsigned long long x10; unsigned long long x11; unsigned long long x12; struct timespec { long long x0; long long x1; } x13; struct timespec { long long x0; long long x1; } x14; struct timespec { long long x0; long long x1; } x15; struct timespec { long long x0; long long x1; } x16; struct timespec { long long x0; long long x1; } x17; struct timespec { long long x0; long long x1; } x18; unsigned int x19; unsigned int x20; } *)fsattributes;

/* instance methods */
- (unsigned int)internalFlags;
- (void)setInternalFlags:(unsigned int)flags;
- (_Bool)isValid:(long long)valid;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)sequenceNumber;
- (id)init;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (void)_setInhibitKernelOffloadedIO:(_Bool)io;
- (id)attrsData;
- (void)getFSAttributes:(struct _FSFileAttributes { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; unsigned long long x9; unsigned long long x10; unsigned long long x11; unsigned long long x12; struct timespec { long long x0; long long x1; } x13; struct timespec { long long x0; long long x1; } x14; struct timespec { long long x0; long long x1; } x15; struct timespec { long long x0; long long x1; } x16; struct timespec { long long x0; long long x1; } x17; struct timespec { long long x0; long long x1; } x18; unsigned int x19; unsigned int x20; } *)fsattributes;
- (_Bool)hasMinimalRequiredAttributes;
- (id)initWithFSAttributes:(const struct _FSFileAttributes { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; unsigned long long x9; unsigned long long x10; unsigned long long x11; unsigned long long x12; struct timespec { long long x0; long long x1; } x13; struct timespec { long long x0; long long x1; } x14; struct timespec { long long x0; long long x1; } x15; struct timespec { long long x0; long long x1; } x16; struct timespec { long long x0; long long x1; } x17; struct timespec { long long x0; long long x1; } x18; unsigned int x19; unsigned int x20; } *)fsattributes;
- (void)invalidateAllProperties;
- (void)setSequenceNumberIfNeeded;

@end

#endif /* FSItemAttributes_h */
