//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSItemPair_h
#define FSItemPair_h
@import Foundation;

@interface FSItemPair : NSObject <NSCopying>

@property (readonly) NSObject *first;
@property (readonly) NSObject *second;

/* class methods */
+ (id)pairWith:(id)with andObject:(id)object;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWith:(id)with andObject:(id)object;

@end

#endif /* FSItemPair_h */
