//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSKitConstants_h
#define FSKitConstants_h
@import Foundation;

@interface FSKitConstants : NSObject

/* class methods */
+ (id)errorTypes;
+ (id)extensionItemTypes;
+ (id)plistAndValueTypes;
+ (id)plistTypes;
+ (id)FSAgentHostXPCProtocol;
+ (id)FSAllClientXPCProtocols;
+ (id)FSClientXPCProtocol;
+ (id)FSModuleExtensionHostXPCProtocol;
+ (id)FSTaskMessageOperations;
+ (id)FSVolumeXPCProtocol;
+ (id)FSAgentXPCProtocol;
+ (id)FSClientHostXPCProtocol;
+ (id)FSKitHelperProtocol;
+ (id)FSModuleExtensionXPCProtocol;
+ (id)FSTaskOperations;
+ (id)fskitdLiveFSMachServiceName;
+ (id)fskitdMachServiceName;
+ (void)setArgumentsForFSClientXPC:(id)xpc;

@end

#endif /* FSKitConstants_h */
