//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSKitHelperProtocol_Protocol_h
#define FSKitHelperProtocol_Protocol_h
@import Foundation;

@protocol FSKitHelperProtocol

@required

/* required instance methods */
- (void)openDevice:(id)device devicePath:(id)path flags:(int)flags auditToken:(id)token replyHandler:(id /* block */)handler;
- (void)revoke:(id)revoke replyHandler:(id /* block */)handler;
- (void)wipeFS:(id)fs replyHandler:(id /* block */)handler;

@optional

@end

#endif /* FSKitHelperProtocol_Protocol_h */
