//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMachPort_h
#define FSMachPort_h
@import Foundation;

@interface FSMachPort : NSObject <NSSecureCoding>

@property (readonly) unsigned int machPort;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)newByCopyingPort:(unsigned int)port;

/* instance methods */
- (id)initWithPort:(unsigned int)port;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (void)dealloc;

@end

#endif /* FSMachPort_h */
