//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMemoryMap_h
#define FSMemoryMap_h
@import Foundation;

@interface FSMemoryMap : NSObject

@property unsigned int port;
@property (readonly) unsigned long long address;
@property (readonly) unsigned long long size;

/* class methods */
+ (id)newWithPort:(unsigned int)port address:(unsigned long long)address andSize:(unsigned long long)size;

/* instance methods */
- (void)dealloc;
- (id)initWithPort:(unsigned int)port address:(unsigned long long)address andSize:(unsigned long long)size;

@end

#endif /* FSMemoryMap_h */
