//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMessageSTDIODelegate_h
#define FSMessageSTDIODelegate_h
@import Foundation;

#include "FSTaskMessageOperations-Protocol.h"

@interface FSMessageSTDIODelegate : NSObject <FSTaskMessageOperations>

@property (readonly, retain) id /* block */ delegate;

/* class methods */
+ (id)delegateWithCompletionHandler:(id /* block */)handler;

/* instance methods */
- (void)logMessage:(id)message;
- (void)completed:(id)completed replyHandler:(id /* block */)handler;
- (void)prompt:(id)prompt replyHandler:(id /* block */)handler;
- (void)promptTrueFalse:(id)_false replyHandler:(id /* block */)handler;

@end

#endif /* FSMessageSTDIODelegate_h */
