//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMessageReceiver_h
#define FSMessageReceiver_h
@import Foundation;

#include "FSMessageReceiverDelegateWrapper.h"

@interface FSMessageReceiver : NSObject <NSXPCListenerDelegate>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) NSXPCListener *listener;
@property (readonly) NSXPCListenerEndpoint *endpoint;
@property (readonly) FSMessageReceiverDelegateWrapper *delegateWrapper;

/* class methods */
+ (id)receiverWithDelegate:(id)delegate;
+ (id)receiverForStandardIO:(id /* block */)io;
+ (id)receiverWithDelegate:(id)delegate locale:(id)locale preferredLanguages:(id)languages;

/* instance methods */
- (_Bool)listener:(id)listener shouldAcceptNewConnection:(id)connection;
- (void)dealloc;
- (id)getConnection;
- (void)didStart;
- (id)initWithDelegate:(id)delegate locale:(id)locale preferredLanguages:(id)languages;

@end

#endif /* FSMessageReceiver_h */
