//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMetadataRange_h
#define FSMetadataRange_h
@import Foundation;

@interface FSMetadataRange : NSObject

@property (readonly) long long startOffset;
@property (readonly) unsigned long long segmentLength;
@property (readonly) unsigned long long segmentCount;

/* class methods */
+ (id)rangeWithOffset:(long long)offset segmentLength:(unsigned long long)length segmentCount:(unsigned long long)count;

/* instance methods */
- (id)initWithOffset:(long long)offset segmentLength:(unsigned long long)length segmentCount:(unsigned long long)count;

@end

#endif /* FSMetadataRange_h */
