//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMessageConnection_h
#define FSMessageConnection_h
@import Foundation;

#include "FSMessageReceiver.h"
#include "FSTaskLocaleOperations-Protocol.h"
#include "FSTaskMessageOperations-Protocol.h"

@protocol OS_dispatch_queue;

@interface FSMessageConnection : NSObject <NSSecureCoding, FSTaskMessageOperations, FSTaskLocaleOperations>

@property (readonly) NSLocale *locale;
@property (copy) id /* block */ earlyCompletedBlock;
@property (copy) id /* block */ lateCompletedBlock;
@property (retain) FSMessageReceiver *receiver;
@property (readonly) NSXPCConnection *connection;
@property (copy) id /* block */ earlyCompletedBlock;
@property (copy) id /* block */ lateCompletedBlock;
@property (readonly) NSXPCConnection *connection;
@property (readonly) NSXPCListenerEndpoint *endpoint;
@property (readonly) _Bool hasCompleted;
@property (readonly) NSArray *preferredLanguages;
@property (retain) FSMessageReceiver *receiver;
@property (readonly) NSLocale *locale;
@property (readonly) NSObject<OS_dispatch_queue> *queue;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithEndpoint:(id)endpoint;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (void)logMessage:(id)message;
- (void)connect:(id /* block */)connect;
- (id)initWithCoder:(id)coder;
- (void)didStart;
- (void)completed:(id)completed replyHandler:(id /* block */)handler;
- (void)completedLocked:(id)locked replyHandler:(id /* block */)handler;
- (void)didCompleteWithError:(id)error completionHandler:(id /* block */)handler;
- (void)getLocalizationSetup:(id /* block */)setup;
- (id)localizedMessage:(id)message table:(id)table bundle:(id)bundle;
- (id)localizedMessage:(id)message table:(id)table bundle:(id)bundle arguments:(char *)arguments;
- (id)localizedMessage:(id)message table:(id)table bundle:(id)bundle array:(id)array;
- (void)logLocalizedMessage:(id)message table:(id)table bundle:(id)bundle;
- (void)logLocalizedMessage:(id)message table:(id)table bundle:(id)bundle arguments:(char *)arguments;
- (void)logLocalizedMessage:(id)message table:(id)table bundle:(id)bundle array:(id)array;
- (void)prompt:(id)prompt replyHandler:(id /* block */)handler;
- (void)promptTrueFalse:(id)_false replyHandler:(id /* block */)handler;

@end

#endif /* FSMessageConnection_h */
