//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMessageReceiverDelegateWrapper_h
#define FSMessageReceiverDelegateWrapper_h
@import Foundation;

#include "FSTaskMessageOperations-Protocol.h"
#include "FSTaskOperations-Protocol.h"

@interface FSMessageReceiverDelegateWrapper : NSObject <FSTaskOperations>

@property (readonly) _Bool hasCompleted;
@property (readonly) _Bool hasStarted;
@property (retain) NSError *completedError;
@property (readonly) NSObject<FSTaskMessageOperations> *delegate;
@property (readonly) NSLocale *locale;
@property (readonly) NSArray *preferredLanguages;

/* instance methods */
- (void)logMessage:(id)message;
- (void)didStart;
- (void)completed:(id)completed replyHandler:(id /* block */)handler;
- (void)getLocalizationSetup:(id /* block */)setup;
- (id)initWithDelegate:(id)delegate Locale:(id)locale preferredLanguages:(id)languages;
- (void)prompt:(id)prompt replyHandler:(id /* block */)handler;
- (void)promptTrueFalse:(id)_false replyHandler:(id /* block */)handler;

@end

#endif /* FSMessageReceiverDelegateWrapper_h */
