//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSModuleExtension_h
#define FSModuleExtension_h
@import Foundation;

#include "FSContainerIdentifier.h"
#include "FSMachPort.h"
#include "FSModuleConnector.h"
#include "FSResource.h"

@class _EXExtension;

@interface FSModuleExtension : _EXExtension <NSXPCListenerDelegate>

@property (readonly) _Bool isFSSubclass;
@property (readonly) _Bool isSimpleFSSubclass;
@property (readonly) _Bool isNormalFS;
@property (readonly) _Bool isSimpleFS;
@property (readonly) _Bool supportsSimpleMaintenanceOps;
@property (readonly) _Bool supportsServerOps;
@property (readonly) _Bool delegateConformantFS;
@property (retain) NSObject *strongDelegate;
@property (retain) FSContainerIdentifier *instanceID;
@property (readonly) NSString *bundleID;
@property (retain) NSMutableDictionary *taskSet;
@property (readonly) NSMutableArray *connectors;
@property (readonly) NSMutableDictionary *volumes;
@property (retain) FSResource *resource;
@property (weak) FSModuleConnector *fskitdCurrentConnection;
@property (retain) FSMachPort *fsMachPort;
@property (readonly, retain, nonatomic) NSXPCListener *secondaryListener;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)fskitdIsClient:(id)client;
+ (id)moduleExtensionForAppex:(id)appex;

/* instance methods */
- (_Bool)listener:(id)listener shouldAcceptNewConnection:(id)connection;
- (_Bool)shouldAcceptConnection:(id)connection;
- (void)didFinishLaunching;
- (void)dealloc;
- (id)getFSMachPort;
- (void)sendConfigureUserClientWithReplyHandler:(id /* block */)handler;
- (void)sendIsVolumeUsed:(id)used bundle:(id)bundle replyHandler:(id /* block */)handler;
- (void)sendWipeResource:(id)resource replyHandler:(id /* block */)handler;

@end

#endif /* FSModuleExtension_h */
