//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSModuleTask_h
#define FSModuleTask_h
@import Foundation;

#include "FSTaskDescription.h"

@interface FSModuleTask : NSObject

@property (copy) NSUUID *taskUUID;
@property (retain) FSTaskDescription *taskDescription;
@property (retain) NSProgress *taskProgress;
@property _Bool wasCanceled;

/* class methods */
+ (id)taskWithID:(id)id description:(id)description progress:(id)progress;

/* instance methods */
- (id)init;
- (id)initWithID:(id)id description:(id)description progress:(id)progress;

@end

#endif /* FSModuleTask_h */
