//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSModuleHostXPC_Protocol_h
#define FSModuleHostXPC_Protocol_h
@import Foundation;

@protocol FSModuleHostXPC <NSObject>

@required

/* required instance methods */
- (void)closeResource:(id)resource replyHandler:(id /* block */)handler;
- (void)configureUserClient:(id)client replyHandler:(id /* block */)handler;
- (void)isVolumeIDUsed:(id)idused bundle:(id)bundle replyHandler:(id /* block */)handler;
- (void)revokeResource:(id)resource replyHandler:(id /* block */)handler;
- (void)taskStatusUpdate:(id)update;
- (void)wipeResource:(id)resource replyHandler:(id /* block */)handler;

@optional

@end

#endif /* FSModuleHostXPC_Protocol_h */
