//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSModuleIdentity_h
#define FSModuleIdentity_h
@import Foundation;

@interface FSModuleIdentity : NSObject <NSSecureCoding>

@property (readonly) NSDictionary *attributes;
@property (readonly) _Bool system;
@property (readonly) NSString *fsShortName;
@property (readonly) NSUUID *uuid;
@property (readonly) NSString *localizedName;
@property (nonatomic) _Bool enabled;
@property (readonly) NSString *teamID;
@property (readonly) NSString *desc;
@property (readonly) NSUUID *uuid;
@property (readonly) NSString *localizedName;
@property (readonly) NSDictionary *attributes;
@property (readonly) _Bool system;
@property (readonly) NSString *teamID;
@property (readonly) NSString *bundleIdentifier;
@property (readonly) NSURL *url;
@property (readonly, nonatomic) _Bool enabled;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (_Bool)isSystem;
- (_Bool)isEnabled;
- (Class)classForCoder;
- (id)description;
- (id)initWithCoder:(id)coder;
- (_Bool)bundleIDIsSystem:(id)system;
- (id)initWithExtensionIdentity:(id)identity isEnabled:(_Bool)enabled;
- (id)initWithExtensionIdentity:(id)identity isEnabled:(_Bool)enabled isSystem:(_Bool)system;

@end

#endif /* FSModuleIdentity_h */
