//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSModuleInstance_h
#define FSModuleInstance_h
@import Foundation;

#include "FSModuleIdentity.h"

@class _EXExtensionIdentity;

@interface FSModuleInstance : NSObject

@property (readonly, nonatomic) FSModuleIdentity *identity;
@property (readonly, nonatomic) _EXExtensionIdentity *exIdentity;
@property (readonly) NSString *bundleIdentifier;
@property (readonly) NSString *bundleVersion;
@property (readonly) NSURL *url;
@property (readonly) NSUUID *UUID;
@property (readonly) NSString *localizedName;
@property (readonly) NSDictionary *attributes;

/* class methods */
+ (id)instanceWithExtensionIdentity:(id)identity;

/* instance methods */
- (id)initWithExtensionIdentity:(id)identity;
- (id)initWithExtensionIdentity:(id)identity;
- (_Bool)isEqual:(id)equal;
- (id)description;
- (id)initWithExtensionIdentity:(id)identity enabled:(_Bool)enabled;
- (id)initWithExtensionRecord:(id)record enabled:(_Bool)enabled;

@end

#endif /* FSModuleInstance_h */
