//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSModuleProjectOperations_Protocol_h
#define FSModuleProjectOperations_Protocol_h
@import Foundation;

@protocol FSModuleProjectOperations <NSObject>

@required

/* required instance methods */
- (void)sendConfigureUserClient:(id)client replyHandler:(id /* block */)handler;
- (void)sendIsVolumeUsed:(id)used bundle:(id)bundle replyHandler:(id /* block */)handler;
- (void)sendWipeResource:(id)resource replyHandler:(id /* block */)handler;

@optional

@end

#endif /* FSModuleProjectOperations_Protocol_h */
