//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSMutableFileDataBuffer_h
#define FSMutableFileDataBuffer_h
@import Foundation;

#include "FSSharedMutableBuffer.h"

@interface FSMutableFileDataBuffer : NSObject <NSSecureCoding> {
    /* instance variables */
    unsigned long long _vma;
    unsigned int _mp;
    unsigned long long _internalCapacity;
}

@property (retain) FSSharedMutableBuffer *proxyOfBuffer;
@property (readonly) unsigned long long length;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)dataWithLength:(unsigned long long)length;
+ (id)dataWithCapacity:(unsigned long long)capacity;

/* instance methods */
- (id)initWithLength:(unsigned long long)length;
- (void *)mutableBytes;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCapacity:(unsigned long long)capacity;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (_Bool)ensureMappedMB:(unsigned long long)mb;
- (_Bool)ensureMapped;
- (id)initProxyFrom:(id)from;
- (id)initWithCapacity:(unsigned long long)capacity andLength:(unsigned long long)length;
- (void)withMutableBytes:(id /* block */)bytes;

@end

#endif /* FSMutableFileDataBuffer_h */
