//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSPathURLResource_h
#define FSPathURLResource_h
@import Foundation;

#include "FSResource.h"

@interface FSPathURLResource : FSResource

@property (retain) NSSecurityScopedURLWrapper *urlWrapper;
@property (readonly, copy) NSURL *url;
@property (readonly) _Bool writable;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)secureResourceWithURL:(id)url readonly:(_Bool)readonly;
+ (id)resourceWithURL:(id)url;

/* instance methods */
- (long long)kind;
- (_Bool)isWritable;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (id)URL;
- (id)initWithURL:(id)url readOnly:(_Bool)only;
- (id)makeProxy;
- (id)getResourceID;
- (id)initAsSecureURL:(id)url readOnly:(_Bool)only;
- (id)initAsSecureURL:(id)url writable:(_Bool)writable;
- (id)initWithURL:(id)url writable:(_Bool)writable;

@end

#endif /* FSPathURLResource_h */
