//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSProbeResult_h
#define FSProbeResult_h
@import Foundation;

#include "FSContainerIdentifier.h"

@interface FSProbeResult : NSObject <NSSecureCoding>

@property (readonly) long long result;
@property (readonly, copy) NSString *name;
@property (readonly) FSContainerIdentifier *containerID;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)cantReadContainerID;
+ (id)newResult:(long long)result name:(id)name containerID:(id)id;
+ (id)notRecognizedProbeResult;
+ (id)recognizedProbeResultWithName:(id)name containerID:(id)id;
+ (id)resultWithResult:(long long)result name:(id)name containerID:(id)id;
+ (id)usableButLimitedProbeResult;
+ (id)usableButLimitedProbeResultWithName:(id)name containerID:(id)id;
+ (id)usableProbeResultWithName:(id)name containerID:(id)id;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)description;
- (id)initWithCoder:(id)coder;
- (id)initWithResult:(long long)result name:(id)name containerID:(id)id;

@end

#endif /* FSProbeResult_h */
