//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSResourceManager_h
#define FSResourceManager_h
@import Foundation;

@interface FSResourceManager : NSObject

@property (retain) NSMutableDictionary *resourceTasks;
@property (retain) NSMutableDictionary *resources;

/* instance methods */
- (id)init;
- (void)addResource:(id)resource;
- (void)updateResource:(id)resource;
- (void)removeResource:(id)resource;
- (id)getResource:(id)resource;
- (void)removeTaskUUID:(id)uuid;
- (void)addTaskUUID:(id)uuid resource:(id)resource;
- (int)getResourceState:(id)state;
- (id)getResources;
- (id)getTaskUUIDs:(id)uuids;

@end

#endif /* FSResourceManager_h */
