//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSResource_h
#define FSResource_h
@import Foundation;

@interface FSResource : NSObject <NSSecureCoding>

@property (readonly, nonatomic) long long kind;
@property (readonly) NSString *resourceID;
@property int state;
@property (readonly) NSURL *progressURLKey;
@property int state;
@property (readonly, nonatomic) _Bool revoked;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)dynamicCast:(id)cast;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (_Bool)isRevoked;
- (id)makeProxy;
- (void)revoke;
- (id)getProgressURLKey;
- (id)getResourceID;
- (id)initResource;

@end

#endif /* FSResource_h */
