//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServerSessionInfoTask_h
#define FSServerSessionInfoTask_h
@import Foundation;

#include "FSServerSessionInfo.h"
#include "FSTask.h"

@interface FSServerSessionInfoTask : FSTask

@property (retain) FSServerSessionInfo *result;

/* instance methods */
- (void)didCompleteWithServerSessionInfo:(id)info;

@end

#endif /* FSServerSessionInfoTask_h */
