//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServerShareInfo_h
#define FSServerShareInfo_h
@import Foundation;

@interface FSServerShareInfo : NSObject <NSSecureCoding, NSCopying>

@property (copy) NSString *displayName;
@property (copy) NSString *connectedByUser;
@property long long howConnected;
@property _Bool alreadyConnected;
@property _Bool hasPassword;
@property _Bool hidden;
@property _Bool printerShare;
@property (copy) NSDictionary *additionalInfo;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isHidden;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (_Bool)isAlreadyConnected;
- (_Bool)isPrinterShare;

@end

#endif /* FSServerShareInfo_h */
