//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSSettings_h
#define FSSettings_h
@import Foundation;

@interface FSSettings : NSObject

@property (readonly, nonatomic) NSURL *settingsContainer;
@property (readonly, nonatomic) NSURL *probeOrderArray;
@property (readonly, nonatomic) NSURL *enabledModulesArray;

/* class methods */
+ (id)defaultSettings;

@end

#endif /* FSSettings_h */
