//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServerURLOperations_Protocol_h
#define FSServerURLOperations_Protocol_h
@import Foundation;

#include "FSServerURLUnaryOperations-Protocol.h"

@protocol FSServerURLOperations <FSServerURLUnaryOperations>

@required

/* required instance methods */
- (id)startConnectingShareWithTask:(id)task server:(id)server share:(id)share options:(id)options error:(id *)error;
- (id)startEnumeratingSharesWithTask:(id)task url:(id)url options:(id)options error:(id *)error;

@optional

@end

#endif /* FSServerURLOperations_Protocol_h */
