//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServerURLResource_h
#define FSServerURLResource_h
@import Foundation;

#include "FSResource.h"

@interface FSServerURLResource : FSResource <NSSecureCoding>

@property (readonly) NSURL *url;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)resourceWithURL:(id)url;

/* instance methods */
- (long long)kind;
- (id)initWithURL:(id)url;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (id)makeProxy;
- (id)getResourceID;

@end

#endif /* FSServerURLResource_h */
