//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServerInfo_h
#define FSServerInfo_h
@import Foundation;

@interface FSServerInfo : NSObject <NSSecureCoding, NSCopying>

@property unsigned long long flags;
@property (copy) NSString *displayName;
@property (copy) NSString *supportedMechTypes;
@property (copy) NSDictionary *authenticationInfo;
@property (copy) NSString *machineType;
@property (copy) NSString *serverOS;
@property (copy) NSString *proxyServerName;
@property (copy) NSString *proxyServerRealm;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;

@end

#endif /* FSServerInfo_h */
