//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServerURLParameters_h
#define FSServerURLParameters_h
@import Foundation;

@interface FSServerURLParameters : NSObject <NSSecureCoding, NSCopying>

@property (copy) NSString *scheme;
@property (copy) NSString *host;
@property (copy) NSNumber *port;
@property (copy) NSString *user;
@property (copy) NSString *password;
@property (copy) NSString *path;
@property (copy) NSString *options;
@property (copy) NSDictionary *extras;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;

@end

#endif /* FSServerURLParameters_h */
