//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSServiceUserClient_h
#define FSServiceUserClient_h
@import Foundation;

#include "FSUserClient.h"

@interface FSServiceUserClient : FSUserClient {
    /* instance variables */
    unsigned int volumePort;
}

/* instance methods */
- (id)init;
- (int)flushMeta:(int)meta wait:(int)wait;
- (int)clearMetaBlocks:(int)blocks ranges:(struct FSKit_Meta_BlockRange_s { long long x0; unsigned int x1; unsigned int x2; } *)ranges rangesCount:(int)count wait:(int)wait;
- (int)writeMeta:(int)meta buffer:(const void *)buffer offset:(long long)offset length:(unsigned long long)length;
- (int)purgeMetaBlocks:(int)blocks ranges:(struct FSKit_Meta_BlockRange_s { long long x0; unsigned int x1; unsigned int x2; } *)ranges rangesCount:(int)count;
- (int)readMeta:(int)meta buffer:(void *)buffer offset:(long long)offset length:(unsigned long long)length;
- (int)readMetaWithRA:(int)ra buffer:(void *)buffer offset:(long long)offset length:(unsigned long long)length raList:(struct FSKit_Meta_Readahead_s { long long x0; unsigned long long x1; } *)list raListCount:(int)count;
- (int)writeMetaDelayed:(int)delayed buffer:(const void *)buffer offset:(long long)offset length:(unsigned long long)length;
- (int)writeMetaSubBlock:(int)block offset:(long long)offset length:(unsigned long long)length subBlockBuffer:(const void *)buffer subBlockOffset:(long long)offset subBlockLength:(unsigned long long)length;
- (int)closeFileDescriptorForKernel:(int)kernel;
- (int)openFileDescriptorForKernel:(int)kernel flags:(int)flags;
- (unsigned int)createVolumePort;
- (unsigned int)getVolumePort;

@end

#endif /* FSServiceUserClient_h */
