//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSSharedMutableBuffer_h
#define FSSharedMutableBuffer_h
@import Foundation;

#include "FSMemoryMap.h"

@interface FSSharedMutableBuffer : NSObject <NSSecureCoding>

@property unsigned long long vma;
@property unsigned long long capacity;
@property unsigned int mp;
@property _Bool isIOWMD;
@property (retain) FSMemoryMap *memMap;
@property unsigned long long length;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)dataWithLength:(unsigned long long)length;
+ (id)dataWithCapacity:(unsigned long long)capacity;
+ (id)bufferWithCapacity:(unsigned long long)capacity;
+ (id)bufferWithLength:(unsigned long long)length;
+ (id)newByCopyingPort:(unsigned int)port;

/* instance methods */
- (id)initWithLength:(unsigned long long)length;
- (void *)mutableBytes;
- (void)encodeWithCoder:(id)coder;
- (const void *)bytes;
- (id)initWithCapacity:(unsigned long long)capacity;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (_Bool)ensureMappedMB:(unsigned long long)mb;
- (id)createDispatchData;
- (void)createMappingAt:(unsigned long long)at options:(unsigned int)options startingAtOffset:(unsigned long long)offset forLength:(unsigned long long)length completionHandler:(id /* block */)handler;
- (void)createMappingForVMAAt:(unsigned long long)vmaat options:(unsigned int)options startingAtOffset:(unsigned long long)offset forLength:(unsigned long long)length completionHandler:(id /* block */)handler;
- (void)detachBytes;
- (_Bool)ensureMapped;
- (_Bool)ensureMappedIOMD;
- (id)initWithCapacity:(unsigned long long)capacity andLength:(unsigned long long)length;
- (id)initWithMachPort:(unsigned int)port capacity:(unsigned long long)capacity length:(unsigned long long)length wrapsIOWMD:(_Bool)iowmd;

@end

#endif /* FSSharedMutableBuffer_h */
