//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSStatFSResult_h
#define FSStatFSResult_h
@import Foundation;

@interface FSStatFSResult : NSObject <NSSecureCoding>

@property long long blockSize;
@property long long ioSize;
@property unsigned long long totalBlocks;
@property unsigned long long availableBlocks;
@property unsigned long long freeBlocks;
@property unsigned long long usedBlocks;
@property unsigned long long totalBytes;
@property unsigned long long availableBytes;
@property unsigned long long freeBytes;
@property unsigned long long usedBytes;
@property unsigned long long totalFiles;
@property unsigned long long freeFiles;
@property long long fileSystemSubType;
@property (readonly, copy) NSString *fileSystemTypeName;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)description;
- (id)initWithCoder:(id)coder;
- (void)_fixUpValues;
- (id)initWithFileSystemTypeName:(id)name;

@end

#endif /* FSStatFSResult_h */
