//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTaskOptionsBundle_h
#define FSTaskOptionsBundle_h
@import Foundation;

#include "FSTaskOptions.h"

@interface FSTaskOptionsBundle : NSObject <NSSecureCoding>

@property (retain) NSMutableDictionary *extras;
@property (readonly, copy) NSArray *options;
@property (readonly, copy) NSArray *parameters;
@property (readonly, copy) FSTaskOptions *taskOptions;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)bundleForArguments:(char * *)arguments count:(int)count extension:(id)extension operationType:(unsigned char)type errorHandler:(id /* block */)handler;
+ (id)bundleForArguments:(char * *)arguments count:(int)count syntaxDictionary:(id)dictionary errorHandler:(id /* block */)handler;
+ (void)resetOptionEnumeration;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)init;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (void)addOption:(id)option;
- (void)enumerateOptionsUsingBlock:(id /* block */)block;
- (id)initWithOptionString:(char * *)string count:(int)count optionDictionary:(id)dictionary operationType:(unsigned char)type errorHandler:(id /* block */)handler;
- (int)mapStringToKind:(id)kind;
- (id)parseAndValidateActivateOptions:(id)options activationSyntax:(id)syntax;

@end

#endif /* FSTaskOptionsBundle_h */
