//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTaskOptions_h
#define FSTaskOptions_h
@import Foundation;

@interface FSTaskOptions : NSObject <NSSecureCoding>

@property (retain) NSMutableDictionary *extras;
@property (copy) NSMutableArray *taskOptions;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithOptions:(id)options;
- (id)initWithCoder:(id)coder;
- (void)setURL:(id)url forKey:(id)key;
- (id)initWithOptions:(id)options extras:(id)extras;
- (void)setSecureURL:(id)url forKey:(id)key;
- (id)urlForOption:(id)option;

@end

#endif /* FSTaskOptions_h */
