//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTaskOption_h
#define FSTaskOption_h
@import Foundation;

@interface FSTaskOption : NSObject <NSSecureCoding>

@property (readonly) _Bool hasValue;
@property (readonly, retain) NSString *option;
@property (readonly, retain) NSString *optionValue;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)option:(id)option value:(id)value;
+ (id)optionWithoutValue:(id)value;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (id)initWithOption:(id)option;
- (id)initWithOption:(id)option value:(id)value;
- (id)initWithOption:(id)option value:(id)value hasValue:(_Bool)value;
- (id)originalArgv;

@end

#endif /* FSTaskOption_h */
