//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTaskOperations_Protocol_h
#define FSTaskOperations_Protocol_h
@import Foundation;

#include "FSTaskLocaleOperations-Protocol.h"
#include "FSTaskMessageOperations-Protocol.h"

@protocol FSTaskOperations <FSTaskMessageOperations, FSTaskLocaleOperations>

@required

@optional

@end

#endif /* FSTaskOperations_Protocol_h */
