//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTaskDescription_h
#define FSTaskDescription_h
@import Foundation;

#include "FSContainerIdentifier.h"
#include "FSResource.h"

@interface FSTaskDescription : NSObject <NSSecureCoding>

@property _Bool taskHasCancellationHandler;
@property (retain) NSObject *taskReferenceHolder;
@property (copy) NSString *taskInitiatorID;
@property (copy) NSString *taskSigningID;
@property _Bool terminateExtensionWhenFinished;
@property (retain) NSObject *taskReferenceHolder;
@property (copy) NSString *taskInitiatorID;
@property (copy) NSString *taskSigningID;
@property _Bool terminateExtensionWhenFinished;
@property _Bool taskHasCancellationHandler;
@property (readonly, copy) NSUUID *taskID;
@property (readonly) unsigned char taskState;
@property (readonly, retain) NSError *taskErrorState;
@property (readonly, copy) NSString *taskBundleID;
@property (readonly, copy) FSContainerIdentifier *taskExtensionInstanceID;
@property (readonly, copy) NSString *taskPurpose;
@property (readonly, copy) FSResource *taskResource;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)taskDescriptionWithID:(id)id state:(unsigned char)state purpose:(id)purpose error:(id)error bundleID:(id)id extensionID:(id)id resource:(id)resource;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (id)initWithCoder:(id)coder;
- (id)initWithID:(id)id state:(unsigned char)state purpose:(id)purpose error:(id)error bundleID:(id)id extensionID:(id)id resource:(id)resource;
- (id)updatedDescriptionInState:(unsigned char)state error:(id)error;

@end

#endif /* FSTaskDescription_h */
