//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTask_h
#define FSTask_h
@import Foundation;

#include "FSMessageConnection.h"
#include "FSTaskMessageOperations-Protocol.h"

@interface FSTask : NSObject <NSSecureCoding, FSTaskMessageOperations>

@property (readonly) NSUUID *taskID;
@property (readonly) FSMessageConnection *connection;
@property (readonly) _Bool hasCancellationHandler;
@property (readonly) FSMessageConnection *connection;
@property (readonly) NSUUID *taskID;
@property (copy) id /* block */ cancellationHandler;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;
- (void)logMessage:(id)message;
- (id)initWithCoder:(id)coder;
- (void)completed:(id)completed replyHandler:(id /* block */)handler;
- (void)didCompleteWithError:(id)error;
- (id)initWithMessageConnection:(id)connection taskID:(id)id;
- (id)localizedMessage:(id)message table:(id)table bundle:(id)bundle arguments:(char *)arguments;
- (void)prompt:(id)prompt replyHandler:(id /* block */)handler;
- (void)promptTrueFalse:(id)_false replyHandler:(id /* block */)handler;

@end

#endif /* FSTask_h */
