//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSTaskMessageSTDIOWithProgress_h
#define FSTaskMessageSTDIOWithProgress_h
@import Foundation;

#include "FSTaskMessageOperations-Protocol.h"

@protocol OS_dispatch_group;

@interface FSTaskMessageSTDIOWithProgress : NSObject <FSTaskMessageOperations> {
    /* instance variables */
    char * progress_buffer;
    int screen_width;
}

@property _Bool progressShowing;
@property _Bool progressHasShown;
@property int twiddleState;
@property (retain) NSObject<OS_dispatch_group> *dispatch_group;
@property (retain, nonatomic) NSProgress *progress;
@property (copy) NSError *completedError;

/* instance methods */
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (id)init;
- (void)logMessage:(id)message;
- (void)dealloc;
- (void)hideProgress;
- (void)showProgress;
- (void)completed:(id)completed replyHandler:(id /* block */)handler;
- (void)fillProgressBar:(float)bar;
- (void)hideProgressLocked;
- (int)printAboveProgress:(const char *)progress;
- (void)prompt:(id)prompt replyHandler:(id /* block */)handler;
- (void)promptTrueFalse:(id)_false replyHandler:(id /* block */)handler;
- (void)showProgressLocked;

@end

#endif /* FSTaskMessageSTDIOWithProgress_h */
