//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSUnaryFileSystemOperations_Protocol_h
#define FSUnaryFileSystemOperations_Protocol_h
@import Foundation;

@protocol FSUnaryFileSystemOperations <NSObject>

@required

/* required instance methods */
- (void)loadResource:(id)resource options:(id)options replyHandler:(id /* block */)handler;
- (void)probeResource:(id)resource replyHandler:(id /* block */)handler;
- (void)unloadResource:(id)resource options:(id)options replyHandler:(id /* block */)handler;

@optional

/* optional instance methods */
- (void)didFinishLoading;

@end

#endif /* FSUnaryFileSystemOperations_Protocol_h */
