//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSUserClient_h
#define FSUserClient_h
@import Foundation;

@interface FSUserClient : NSObject {
    /* instance variables */
    unsigned int ourPort;
}

/* class methods */
+ (id)defaultClient;

/* instance methods */
- (id)init;
- (void)dealloc;
- (int)callStructMethod:(unsigned int)method inStruct:(const void *)_struct inSize:(unsigned long long)size outStruct:(void *)_struct outStructSize:(unsigned long long *)size;
- (int)checkUserClientPort;
- (int)configureUserClient:(unsigned int)client pid:(int)pid pidversion:(int)pidversion supportBlockResource:(int)resource;
- (unsigned int)getConnPort;
- (int)getUserClientPort;
- (int)getUserClientPortForService:(const char *)service;
- (int)setMainMachPort:(unsigned int)port forDomain:(id)domain;

@end

#endif /* FSUserClient_h */
