//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSVolumeRenameOperations_Protocol_h
#define FSVolumeRenameOperations_Protocol_h
@import Foundation;

@protocol FSVolumeRenameOperations <NSObject>

@required

/* required instance methods */
- (void)setVolumeName:(id)name replyHandler:(id /* block */)handler;

@optional

@property _Bool volumeRenameInhibited;

/* optional instance methods */
- (_Bool)isVolumeRenameInhibited;

@end

#endif /* FSVolumeRenameOperations_Protocol_h */
