//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSVolume_h
#define FSVolume_h
@import Foundation;

#include "FSFileName.h"
#include "FSVolumeIdentifier.h"

@interface FSVolume : NSObject

@property (retain) FSVolumeIdentifier *volumeID;
@property (nonatomic) long long state;
@property (nonatomic) _Bool wasTerminated;
@property (copy) FSFileName *name;

/* instance methods */
- (id)initWithVolumeID:(id)id volumeName:(id)name;

@end

#endif /* FSVolume_h */
