//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSVolumeDescription_h
#define FSVolumeDescription_h
@import Foundation;

#include "FSFileName.h"
#include "FSVolumeIdentifier.h"

@interface FSVolumeDescription : NSObject <NSSecureCoding, NSCopying>

@property (readonly, copy) FSVolumeIdentifier *volumeID;
@property (readonly, copy) FSFileName *volumeName;
@property (readonly) long long volumeState;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)volumeDescriptionWithID:(id)id name:(id)name state:(long long)state;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (id)description;
- (id)initWithCoder:(id)coder;
- (id)initWithID:(id)id name:(id)name state:(long long)state;

@end

#endif /* FSVolumeDescription_h */
