//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSVolumeOpenCloseOperations_Protocol_h
#define FSVolumeOpenCloseOperations_Protocol_h
@import Foundation;

@protocol FSVolumeOpenCloseOperations <NSObject>

@required

/* required instance methods */
- (void)closeItem:(id)item keepingModes:(unsigned long long)modes replyHandler:(id /* block */)handler;
- (void)openItem:(id)item withModes:(unsigned long long)modes replyHandler:(id /* block */)handler;

@optional

@property _Bool openCloseInhibited;

/* optional instance methods */
- (_Bool)isOpenCloseInhibited;

@end

#endif /* FSVolumeOpenCloseOperations_Protocol_h */
