//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSVolumeAccessCheckOperations_Protocol_h
#define FSVolumeAccessCheckOperations_Protocol_h
@import Foundation;

@protocol FSVolumeAccessCheckOperations <NSObject>

@required

/* required instance methods */
- (void)checkAccessToItem:(id)item requestedAccess:(unsigned long long)access replyHandler:(id /* block */)handler;

@optional

@property _Bool accessCheckInhibited;

/* optional instance methods */
- (_Bool)isAccessCheckInhibited;

@end

#endif /* FSVolumeAccessCheckOperations_Protocol_h */
