//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSVolumeReadWriteOperations_Protocol_h
#define FSVolumeReadWriteOperations_Protocol_h
@import Foundation;

@protocol FSVolumeReadWriteOperations <NSObject>

@required

/* required instance methods */
- (void)readFromFile:(id)file offset:(long long)offset length:(unsigned long long)length intoBuffer:(id)buffer replyHandler:(id /* block */)handler;
- (void)writeContents:(id)contents toFile:(id)file atOffset:(long long)offset replyHandler:(id /* block */)handler;

@optional

@end

#endif /* FSVolumeReadWriteOperations_Protocol_h */
