//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef FSWorkQueue_h
#define FSWorkQueue_h
@import Foundation;

@interface FSWorkQueue : NSObject

@property (retain) NSMutableArray *queues;
@property int index;
@property int concurrency;
@property (retain) NSString *domain;
@property _Bool didInitQueues;

/* instance methods */
- (void)enqueue:(id /* block */)enqueue;
- (id)initQueueWithDomain:(id)domain concurrency:(int)concurrency;
- (void)initQueues;

@end

#endif /* FSWorkQueue_h */
