//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef NSArray_FSKitAdditions_h
#define NSArray_FSKitAdditions_h
@import Foundation;

@interface NSArray (FSKitAdditions)

/* instance methods */
- (id)fs_map:(id /* block */)fs_map;
- (_Bool)fs_all_of:(id /* block */)fs_all_of;
- (_Bool)fs_any_of:(id /* block */)fs_any_of;
- (id)fs_filter:(id /* block */)fs_filter;
- (id)fs_mapWithIndex:(id /* block */)index;

@end

#endif /* NSArray_FSKitAdditions_h */
