//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef NSString_FSFileHandle_h
#define NSString_FSFileHandle_h
@import Foundation;

@interface NSString (FSFileHandle)

/* instance methods */
- (id)fsFileHandle;

@end

#endif /* NSString_FSFileHandle_h */
