//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSGatedWork_h
#define LiveFSGatedWork_h
@import Foundation;

@interface LiveFSGatedWork : NSObject

@property (copy) id /* block */ workBlock;
@property long long neededCount;
@property (retain) NSObject *parameter;

/* instance methods */
- (void)abort;
- (void)approve;
- (id)initWithCount:(long long)count workBlock:(id /* block */)block;

@end

#endif /* LiveFSGatedWork_h */
