//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSMountClient_h
#define LiveFSMountClient_h
@import Foundation;

@protocol LiveFSMounterClient;

@interface LiveFSMountClient : NSObject {
    /* instance variables */
    NSXPCConnection *conn;
    NSString *provider;
    NSObject<LiveFSMounterClient> *helper;
}

/* class methods */
+ (id)newClient;
+ (id)newClientForProvider:(id)provider;

/* instance methods */
- (id)initWithProvider:(id)provider;
- (void)setConnection:(id)connection;
- (void)dealloc;
- (id)mounts:(id *)mounts;
- (id)allMounts:(id *)mounts;
- (id)fixupConnectionFor:(id)_for;
- (id)mountVolume:(id)volume displayName:(id)name provider:(id)provider domainError:(id)error on:(id)on how:(int)how;
- (id)mountVolume:(id)volume displayName:(id)name provider:(id)provider domainError:(id)error on:(id)on how:(unsigned long long)how options:(id)options;
- (id)mountVolume:(id)volume displayName:(id)name provider:(id)provider on:(id)on how:(int)how;
- (id)mountVolume:(id)volume fileSystem:(id)system displayName:(id)name provider:(id)provider domainError:(id)error on:(id)on how:(unsigned long long)how options:(id)options;
- (id)mountVolume:(id)volume fileSystem:(id)system displayName:(id)name provider:(id)provider domainError:(id)error on:(id)on how:(unsigned long long)how options:(id)options auditToken:(struct { unsigned int x0[8]; })token;
- (id)setVerboseLevel:(int)level;
- (id)unmountVolume:(id)volume how:(int)how;
- (id)unmountVolumeByID:(unsigned int)id how:(int)how;
- (id)updateErrorStateForVolume:(id)volume provider:(id)provider domainError:(id)error;
- (int)verboseLevelOrError:(id *)error;

@end

#endif /* LiveFSMountClient_h */
