//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSRBTree_h
#define LiveFSRBTree_h
@import Foundation;

@interface LiveFSRBTree : NSObject {
    /* instance variables */
    id /* block */ ourComparitor;
    struct rb_tree { void *x0[8]; } * btree;
    struct { void * /* function */ x0; void * /* function */ x1; unsigned long long x2; void *x3; } * btOps;
}

@property (retain) NSMutableArray *ourData;

/* class methods */
+ (id)newWithComparitor:(id /* block */)comparitor;

/* instance methods */
- (unsigned long long)count;
- (void)addEntry:(long long)entry;
- (void)dealloc;
- (void)addDataBuffer:(id)buffer;
- (id)extractItemsInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range withBlock:(id /* block */)block;
- (id)initWithComparitor:(id /* block */)comparitor;

@end

#endif /* LiveFSRBTree_h */
