//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSVolumeSearch_Protocol_h
#define LiveFSVolumeSearch_Protocol_h
@import Foundation;

@protocol LiveFSVolumeSearch

@required

/* required instance methods */
- (void)searchResults:(id)results paths:(id)paths attributes:(id)attributes attributeSize:(unsigned int)size xAttrs:(id)attrs resumePath:(id)path;
- (void)tokenDone:(id)done result:(int)result;

@optional

@end

#endif /* LiveFSVolumeSearch_Protocol_h */
