//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSLRUCache_h
#define LiveFSLRUCache_h
@import Foundation;

@interface LiveFSLRUCache : NSObject

@property (retain) NSMutableDictionary *mapping;
@property (retain) NSMutableArray *usageOrder;
@property int countLimit;

/* instance methods */
- (void)removeAllObjects;
- (id)objectForKey:(id)key;
- (void)removeObjectForKey:(id)key;
- (id)init;
- (void)setObject:(id)object forKey:(id)key;
- (id)objectForKeyLocked:(id)locked;
- (void)removeLastItem;

@end

#endif /* LiveFSLRUCache_h */
