//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSItemPair_h
#define LiveFSItemPair_h
@import Foundation;

@interface LiveFSItemPair : NSObject <NSCopying>

@property (readonly) NSString *itemId;
@property (readonly) NSString *filename;

/* class methods */
+ (id)newWithParent:(id)parent fname:(id)fname;
+ (id)newWithParent:(id)parent fname:(id)fname caseSensitivity:(_Bool)sensitivity;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWithParent:(id)parent fname:(id)fname caseSensitivity:(_Bool)sensitivity;

@end

#endif /* LiveFSItemPair_h */
