//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSUnlock_Protocol_h
#define LiveFSUnlock_Protocol_h
@import Foundation;

@protocol LiveFSUnlock <NSObject>

@required

/* required instance methods */
- (void)unlockWithPassword:(id)password saveToKeychain:(_Bool)keychain completionHandler:(id /* block */)handler;

@optional

@end

#endif /* LiveFSUnlock_Protocol_h */
