//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef LiveFSIDHelper_h
#define LiveFSIDHelper_h
@import Foundation;

@interface LiveFSIDHelper : NSObject

/* class methods */
+ (unsigned long long)rootItemID;
+ (id)identifierForItem:(unsigned long long)item name:(id)name parentID:(unsigned long long)id;

@end

#endif /* LiveFSIDHelper_h */
