//
//   Generated by https://github.com/blacktop/ipsw (Version: v0.0.0-prerelease, BuildCommit: 2c9aa165c)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 737.120.9.0.0
//
#ifndef stolenUSBLocalStorageClient_h
#define stolenUSBLocalStorageClient_h
@import Foundation;

#include "LiveFSClient.h"

@interface stolenUSBLocalStorageClient : LiveFSClient

/* class methods */
+ (id)newManager;

/* instance methods */
- (id)loadVolumes:(id)volumes ofType:(id)type withError:(id *)error;

@end

#endif /* stolenUSBLocalStorageClient_h */
